### ISSUE TITLE
Error at publishing to skydroid

### ISSUE THREAD

**Issue by MicMun** [redsolver/skydroid-cli#3]
I have an android app with app/build.gradle:
```
      versionCode 200
      versionName "2.0.0"
```

In the skydroid-dev.yaml I have:
```
checkVersion:
  file: app/build.gradle
  versionCode: 'versionCode.+(\d+)$'
  versionName: 'versionName.+"(.+)"$'
```

But _skydroid publish --verbose_ gives the folling output:

```
Publishing SkyDroid app in XXX...
Oops, something went wrong: Bad state: No element
#0      Iterable.first (dart:core/iterable.dart:524)
#1      PublishCommand.run (package:skydroid_cli/commands/publish.dart:87)
#2      CommandRunner.runCommand (package:args/command_runner.dart:197)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112)
#4      new Future.sync (dart:async/future.dart:223)
#5      CommandRunner.run (package:args/command_runner.dart:112)
#6      main (file:///home/runner/work/skydroid-cli/skydroid-cli/bin/skydroid.dart:23)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)
```

**Comment by redsolver** [comment]
Sorry, the correct configuration for `skydroid-dev.yaml` is
```yaml
checkVersion:
  file: app/build.gradle
  versionCode: 'versionCode\s+(\d+)'
  versionName: 'versionName.+"(.+)"'
  ```
  I'll push an update to the CLI soon to fix this by default
